#I have no idea how to write a yaml file or if this will even work, but what the hey

runtime: java
env: standard
runtime_config:
  jdk: openjdk11
env_variables:
  SPRING_PROFILES_ACTIVE: "production"
handlers:
- url: /.*
  script: this field is required, but ignored
manual_scaling:
  instances: 1